site_name: Fudge
site_url: https://danielc.dev/fudge
site_description: Fudge is an open-source alternative to Fujifilm's camera pairing app
site_author: Daniel Cook

repo_url: https://github.com/petabyt/fudge
edit_uri: ""

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
  palette:
    scheme: slate
  logo: fastlane/metadata/android/en-US/images/icon.png
  hide:
    - navigation
    - toc

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - FAQ: help.md
  - News: blog/index.md
  - dev.md

plugins:
  - blog
