name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: secrets
    container:
      image: ghcr.io/petabyt/fudge:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      packages: read
    steps:
    - uses: actions/checkout@v4
    - name: Pull submodules
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git submodule update --init --recursive --recommend-shallow
    - name: Update to latest module versions
      run: |
        cd modules/libfuji && git pull origin master --recurse-submodules
    - name: Build and sign with Gradle
      timeout-minutes: 15
      env:
        KEYSTORE_FILE: release-key.jks
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        echo "${{ secrets.KEYSTORE_B64 }}" | base64 --decode > app/release-key.jks
        bash gradlew assembleRelease
    - name: Upload Latest Pre-release
      if: github.event_name != 'pull_request'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "app/build/outputs/apk/nightly/release/*.apk"
        tag: "latest"
        name: "Nightly Build"
        bodyFile: ".github/workflows/nightly.txt"
        prerelease: true
        allowUpdates: true
        replacesArtifacts: true
        commit: ${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
